### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sunset9899** [JanRotti/pod_galerkin#1]
I am interested in your "podGalerkin" code ,actually i am new postgraduate student. I dont know what  the ".su2" file's structure is . I would be very appreciated if the author could tell me about this .

**Comment by JanRotti** [comment]
I highly recommend reading the [official documentation](https://su2code.github.io/docs_v7/Mesh-File/) to the SU2 native format ".su2". The format is based on a mesh description used by the SU2 software.

**Comment by sunset9899** [comment]
very thanks for your reply. it helps a lot&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jan ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 晚上8:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JanRotti/podGalerkin] question (Issue #1)





 
I highly recommend reading the official documentation to the SU2 native format ".su2". The format is based on a mesh description used by the SU2 software.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhengtu111** [comment]
I am interested in your podGalerkin code ,actually i am new postgraduate student. I dont know what the Dir “'./flow_data/lam_cyl_comp_air/mach 0.6 chirp/'” is . I would be very appreciated if the author could tell me about this .

**Comment by JanRotti** [comment]
Continued in #2

**Comment by zhengtu111** [comment]
Thanks for your reply very much.
