### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhengtu111** [JanRotti/pod_galerkin#2]
I am interested in your pod Galerkin code, but I'm a new graduate student who doesn't know much about POD Galerkin, and I ran into a bit of a problem looking at your code. This path './flow_data/lam_cyl_comp_air/mach 0.6 chirp/' could not be found, I would appreciate it if you could help me answer this question. Thank you very much.

**Comment by JanRotti** [comment]
**All** the data, that I used, is not provided by the code. If you want to generate some I can recommend SU2; Although SU2 does not support the option to apply a moving wall function (which is necessary), this can be easily added in the code.
